/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.me.pokemongame;

import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author nikos
 */
public class ChallengeFrame extends javax.swing.JFrame {
private int playerNumber;
    private int battleWithPlayer;
    /**
     * Creates new form ChallengeFrame
     */
    public ChallengeFrame(int aplayerNumber) {
       this.playerNumber=aplayerNumber;
        initComponents();
        myinitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel2.setText("Choose the player to battle with:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 280, 28);

        jRadioButton5.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Player 5");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(90, 80, 80, 30);

        jRadioButton1.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Player 1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(0, 60, 80, 20);

        jRadioButton2.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Player 2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(0, 75, 80, 40);

        jRadioButton3.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Player 3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(0, 110, 80, 23);

        jRadioButton6.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Player 6");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(90, 110, 90, 23);

        jRadioButton4.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Player 4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(90, 55, 80, 30);

        jRadioButton7.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Master Trainer");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(170, 80, 120, 23);

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 130, 272, 28);

        jRadioButton9.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setText("YES");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton9);
        jRadioButton9.setBounds(0, 160, 60, 23);

        jRadioButton10.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup2.add(jRadioButton10);
        jRadioButton10.setText("NO");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(70, 160, 50, 23);

        jButton1.setText(" Start Battle!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 200, 130, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed

        boolean a=false;
        for(int i=0;i<PlayerFrame.caughtPokemon5.size();i++){
            if(PlayerFrame.caughtPokemon5.get(i).isAlive()){
                a=true;
                break;
            }
         
            
            
            
        }
        if(!a){
            JOptionPane.showMessageDialog(rootPane, "All your Pokemon are fainted ", "Sorry! ", WIDTH);
            dispose();

        }for(int i=0; i<PlayerFrame.objectCard5.size(); i++){
            if(PlayerFrame.objectCard5.get(i).getName()=="PokeDoll"){
                jLabel3.setVisible(true);
                jRadioButton9.setVisible(true);
                jRadioButton10.setVisible(true);
            }
        }
        battleWithPlayer=5;
        jLabel3.setText("Will player 5 use his PokeDoll?");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        boolean a=false;
        for(int i=0;i<PlayerFrame.caughtPokemon1.size();i++){
            if(PlayerFrame.caughtPokemon1.get(i).isAlive()){
                a=true;
                break;
            }
         
            
            
            
        }
        if(!a){
            JOptionPane.showMessageDialog(rootPane, "All your Pokemon are fainted ", "Sorry! ", WIDTH);
            dispose();

        }for(int i=0; i<PlayerFrame.objectCard1.size(); i++){
            if(PlayerFrame.objectCard1.get(i).getName()=="PokeDoll"){
                jLabel3.setVisible(true);
                jRadioButton9.setVisible(true);
                jRadioButton10.setVisible(true);
            }
        }
        battleWithPlayer=1;
        jLabel3.setText("Will player 1 use his PokeDoll?");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        boolean a=false;
        for(int i=0;i<PlayerFrame.caughtPokemon2.size();i++){
            if(PlayerFrame.caughtPokemon2.get(i).isAlive()){
                a=true;
                break;
            }
         
            
            
            
        }
        if(!a){
            JOptionPane.showMessageDialog(rootPane, "All your Pokemon are fainted ", "Sorry! ", WIDTH);
            dispose();

        }for(int i=0; i<PlayerFrame.objectCard2.size(); i++){
            if(PlayerFrame.objectCard2.get(i).getName()=="PokeDoll"){
                jLabel3.setVisible(true);
                jRadioButton9.setVisible(true);
                jRadioButton10.setVisible(true);
            }
        }
        battleWithPlayer=2;
        jLabel3.setText("Will player 2 use his PokeDoll?");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

        boolean a=false;
        for(int i=0;i<PlayerFrame.caughtPokemon3.size();i++){
            if(PlayerFrame.caughtPokemon3.get(i).isAlive()){
                a=true;
                break;
            }
         
            
            
            
        }
        if(!a){
            JOptionPane.showMessageDialog(rootPane, "All your Pokemon are fainted ", "Sorry! ", WIDTH);
            dispose();

        }for(int i=0; i<PlayerFrame.objectCard3.size(); i++){
            if(PlayerFrame.objectCard3.get(i).getName()=="PokeDoll"){
                jLabel3.setVisible(true);
                jRadioButton9.setVisible(true);
                jRadioButton10.setVisible(true);
            }
        }
        battleWithPlayer=3;
        jLabel3.setText("Will player 3 use his PokeDoll?");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed

        boolean a=false;
        for(int i=0;i<PlayerFrame.caughtPokemon6.size();i++){
            if(PlayerFrame.caughtPokemon6.get(i).isAlive()){
                a=true;
                break;
            }
         
            
            
            
        }
        if(!a){
            JOptionPane.showMessageDialog(rootPane, "All your Pokemon are fainted ", "Sorry! ", WIDTH);
            dispose();

        }for(int i=0; i<PlayerFrame.objectCard6.size(); i++){
            if(PlayerFrame.objectCard6.get(i).getName()=="PokeDoll"){
                jLabel3.setVisible(true);
                jRadioButton9.setVisible(true);
                jRadioButton10.setVisible(true);
            }
        }
        battleWithPlayer=6;
        jLabel3.setText("Will player 6 use his PokeDoll?");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed

        boolean a=false;
        for(int i=0;i<PlayerFrame.caughtPokemon4.size();i++){
            if(PlayerFrame.caughtPokemon4.get(i).isAlive()){
                a=true;
                break;
            }
         
            
            
            
        }
        if(!a){
            JOptionPane.showMessageDialog(rootPane, "All your Pokemon are fainted ", "Sorry! ", WIDTH);
            dispose();

        }for(int i=0; i<PlayerFrame.objectCard4.size(); i++){
            if(PlayerFrame.objectCard4.get(i).getName()=="PokeDoll"){
                jLabel3.setVisible(true);
                jRadioButton9.setVisible(true);
                jRadioButton10.setVisible(true);
            }
        }
        battleWithPlayer=4;
        jLabel3.setText("Will player 4 use his PokeDoll?");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        int i=0;

        switch(battleWithPlayer){
            case 1:
            boolean poke1=false;
            for(i=0; i<PlayerFrame.objectCard1.size(); i++ ){

                if(PlayerFrame.objectCard1.get(i).getName()=="PokeDoll")
                {
                    poke1=true;
                    PlayerFrame.objectCard1.remove(PlayerFrame.objectCard1.remove(i));
                    PlayerFrame.Cardcombobox1.removeItem("PokeDoll");
                }

                if(poke1)  {PlayerFrame.DrawObjectButton1.setEnabled(true); break;}

            }
            break;
            case 2:   boolean poke2=false;
            for(i=0; i<PlayerFrame.objectCard2.size(); i++ ){

                if(PlayerFrame.objectCard2.get(i).getName()=="PokeDoll")
                {
                    poke2=true;
                    PlayerFrame.objectCard2.remove(PlayerFrame.objectCard2.remove(i));
                    PlayerFrame.Cardcombobox2.removeItem("PokeDoll");
                }

                if(poke2)  {PlayerFrame.DrawObjectButton2.setEnabled(true); break;}

            }
            break;
            case 3: boolean poke3=false;
            for(i=0; i<PlayerFrame.objectCard3.size(); i++ ){

                if(PlayerFrame.objectCard3.get(i).getName()=="PokeDoll")
                {
                    poke3=true;
                    PlayerFrame.objectCard3.remove(PlayerFrame.objectCard3.remove(i));
                    PlayerFrame.Cardcombobox3.removeItem("PokeDoll");
                }

                if(poke3)  {PlayerFrame.DrawObjectButton3.setEnabled(true); break;}

            }
            break;
            case 4:  boolean poke4=false;
            for(i=0; i<PlayerFrame.objectCard4.size(); i++ ){

                if(PlayerFrame.objectCard4.get(i).getName()=="PokeDoll")
                {
                    poke4=true;
                    PlayerFrame.objectCard4.remove(PlayerFrame.objectCard4.remove(i));
                    PlayerFrame.Cardcombobox4.removeItem("PokeDoll");
                }

                if(poke4)  {PlayerFrame.DrawObjectButton4.setEnabled(true); break;}

            }
            break;
            case 5:  boolean poke5=false;
            for(i=0; i<PlayerFrame.objectCard5.size(); i++ ){

                if(PlayerFrame.objectCard5.get(i).getName()=="PokeDoll")
                {
                    poke5=true;
                    PlayerFrame.objectCard5.remove(PlayerFrame.objectCard5.remove(i));
                    PlayerFrame.Cardcombobox5.removeItem("PokeDoll");
                }

                if(poke5)  {PlayerFrame.DrawObjectButton5.setEnabled(true); break;}

            }
            break;
            case 6: boolean poke6=false;
            for(i=0; i<PlayerFrame.objectCard6.size(); i++ ){

                if(PlayerFrame.objectCard6.get(i).getName()=="PokeDoll")
                {
                    poke6=true;
                    PlayerFrame.objectCard6.remove(PlayerFrame.objectCard6.remove(i));
                    PlayerFrame.Cardcombobox6.removeItem("PokeDoll");
                }

                if(poke6)  {PlayerFrame.DrawObjectButton6.setEnabled(true); break;}

            }
            break;
        }
                                            JOptionPane.showMessageDialog(rootPane, "A Pokedoll has been used, battle cancelled ", "Sorry! ", WIDTH);

        this.dispose();

    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
battleWithPlayer=7;//master trainer    }//GEN-LAST:event_jRadioButton7ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new BattleFrame(playerNumber, battleWithPlayer).setVisible(true);

dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables

    private void myinitComponents() {
        
         jLabel3.setVisible(false);
      jRadioButton9.setVisible(false);
      jRadioButton10.setVisible(false);
      switch(playerNumber){
        case 1: jRadioButton1.setVisible(false);
            break;
             case 2: jRadioButton2.setVisible(false);
            break;
                  case 3: jRadioButton3.setVisible(false);
            break;
                       case 4: jRadioButton4.setVisible(false);
            break;
                            case 5: jRadioButton5.setVisible(false);
            break;
                                 case 6: jRadioButton6.setVisible(false);
            break;
    }
      switch(PlayerFrame.numberOfPlayers){
       
             case 2: jRadioButton3.setVisible(false);
                     jRadioButton4.setVisible(false);
                     jRadioButton5.setVisible(false);
                     jRadioButton6.setVisible(false);
            break;
                  case 3: jRadioButton4.setVisible(false);
                  jRadioButton5.setVisible(false);
                  jRadioButton6.setVisible(false);
            break;
                       case 4: jRadioButton5.setVisible(false);
                       jRadioButton6.setVisible(false);
                       
            break;
                            case 5: jRadioButton6.setVisible(false);
            break;
            
    }
}}

