/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.me.pokemongame;

import java.util.Random;
import static org.me.pokemongame.PlayerFrame.Pokemoncombobox1;
import static org.me.pokemongame.PokemonTapaFrame.p;
import static org.me.pokemongame.PokemonTapaFrame.toBeCaught;

/**
 *
 * @author nikos
 */
public class KartaTyxisFrame extends javax.swing.JFrame {
private int numberOfPlayer;
private String color;
private Pokemon kp=null;
    /**
     * Creates new form KartaTyxisFrame
     */
    public KartaTyxisFrame(int anumberOfPlayer) {
       this.numberOfPlayer=anumberOfPlayer;
        initComponents();
                myinitComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(330, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 650));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(330, 650));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select the color you are on:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(44, 264, 177, 24);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 153, 153));
        jRadioButton1.setText("PINK");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(10, 290, 63, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 204, 0));
        jRadioButton2.setText("GREEN");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(110, 290, 75, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 153, 204));
        jRadioButton3.setText("BLUE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(10, 310, 63, 25);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton4.setText("RED");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(110, 310, 55, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(10, 370, 180, 20);

        jLabel3.setText("Open Pokemon Chips:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 340, 180, 30);

        jButton1.setText("I choose you!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(190, 370, 120, 20);

        jButton2.setText("Choose Random");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(90, 440, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("OR");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 404, 110, 30);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/pokemongame/Chansey.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(330, 650));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
color="pink";
 jComboBox1.removeAllItems();
for(int i=0; i<PokemonTapaFrame.toBeCaught.size(); i++){
    if(PokemonTapaFrame.toBeCaught.get(i).getColor()==color)
    {
        jComboBox1.addItem(PokemonTapaFrame.toBeCaught.get(i).getName());
    }
}
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
color="green";
 jComboBox1.removeAllItems();

for(int i=0; i<PokemonTapaFrame.toBeCaught.size(); i++){
    if(PokemonTapaFrame.toBeCaught.get(i).getColor()==color)
    {
        jComboBox1.addItem(PokemonTapaFrame.toBeCaught.get(i).getName());
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
color="blue";
 jComboBox1.removeAllItems();

for(int i=0; i<PokemonTapaFrame.toBeCaught.size(); i++){
    if(PokemonTapaFrame.toBeCaught.get(i).getColor()==color)
    {
        jComboBox1.addItem(PokemonTapaFrame.toBeCaught.get(i).getName());
    }
}    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
color="red";
 jComboBox1.removeAllItems();

for(int i=0; i<PokemonTapaFrame.toBeCaught.size(); i++){
    if(PokemonTapaFrame.toBeCaught.get(i).getColor()==color)
    {
        jComboBox1.addItem(PokemonTapaFrame.toBeCaught.get(i).getName());
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Random r=new Random();
        int index=0;
        switch (color) {
            case "pink":  
        
         index = r.nextInt(Pokemon.pinkArray.size());
         kp = Pokemon.pinkArray.get(index);
         
        Pokemon.pinkArray.remove(kp);

           
                     break;
                
            case "green":   
                
        index = r.nextInt(Pokemon.greenArray.size());
         kp = Pokemon.greenArray.get(index);

        Pokemon.greenArray.remove(kp);

                     break;
                
        case "blue":  
            
        index = r.nextInt(Pokemon.blueArray.size());
         kp = Pokemon.blueArray.get(index);
         

        Pokemon.blueArray.remove(kp);
        
                     break;
                
            case "red":  
                
        index = r.nextInt(Pokemon.redArray.size());
         kp = Pokemon.redArray.get(index);
         
        Pokemon.redArray.remove(kp);
        
                     break;
        }
        
        switch(numberOfPlayer)
        {
            case 1: PlayerFrame.caughtPokemon1.add(kp);
            PlayerFrame.Pokemoncombobox1.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon1.size(); j++){
            
            PlayerFrame.Pokemoncombobox1.addItem(PlayerFrame.caughtPokemon1.get(j).getName());

                    
                 
            
        }
                break;
                case 2: PlayerFrame.caughtPokemon2.add(kp);
            PlayerFrame.Pokemoncombobox2.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon2.size(); j++){
            
            PlayerFrame.Pokemoncombobox2.addItem(PlayerFrame.caughtPokemon2.get(j).getName());

                    
                 
            
        }
                break;
                     case 3: PlayerFrame.caughtPokemon3.add(kp);
            PlayerFrame.Pokemoncombobox3.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon3.size(); j++){
            
            PlayerFrame.Pokemoncombobox3.addItem(PlayerFrame.caughtPokemon3.get(j).getName());

                    
                 
            
        }
                break;
                          case 4: PlayerFrame.caughtPokemon4.add(kp);
            PlayerFrame.Pokemoncombobox4.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon4.size(); j++){
            
            PlayerFrame.Pokemoncombobox4.addItem(PlayerFrame.caughtPokemon4.get(j).getName());

                    
                 
            
        }
                break;
                               case 5: PlayerFrame.caughtPokemon5.add(kp);
            PlayerFrame.Pokemoncombobox5.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon5.size(); j++){
            
            PlayerFrame.Pokemoncombobox5.addItem(PlayerFrame.caughtPokemon5.get(j).getName());

                    
                 
            
        }
                break;
                                    case 6: PlayerFrame.caughtPokemon6.add(kp);
            PlayerFrame.Pokemoncombobox6.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon6.size(); j++){
            
            PlayerFrame.Pokemoncombobox6.addItem(PlayerFrame.caughtPokemon6.get(j).getName());

                    
                 
            
        }
                break;
        }
        PlayerFrame.caughtPokemon.add(kp);
        new ShowPokemonFrame(kp.getName(),0).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String selected=(String) jComboBox1.getSelectedItem();
        for(int i=0; i<PokemonTapaFrame.toBeCaught.size(); i++){
            if(PokemonTapaFrame.toBeCaught.get(i).getName()==selected)
            {
                kp=PokemonTapaFrame.toBeCaught.get(i);
        }
        }
            PlayerFrame.caughtPokemon.add(kp);
            PokemonTapaFrame.toBeCaught.remove(kp);
             switch(numberOfPlayer){
            case 1: PlayerFrame.caughtPokemon1.add(kp);
                 PlayerFrame.Pokemoncombobox1.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon1.size(); j++){
            
            PlayerFrame.Pokemoncombobox1.addItem(PlayerFrame.caughtPokemon1.get(j).getName());

                    
                 
            
        }
            break;
                case 2: PlayerFrame.caughtPokemon2.add(kp);
                 PlayerFrame.Pokemoncombobox2.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon2.size(); j++){
            
            PlayerFrame.Pokemoncombobox2.addItem(PlayerFrame.caughtPokemon2.get(j).getName());

                    
                 
            
        }
            break;
                    case 3: PlayerFrame.caughtPokemon3.add(kp);
                 PlayerFrame.Pokemoncombobox3.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon3.size(); j++){
            
            PlayerFrame.Pokemoncombobox3.addItem(PlayerFrame.caughtPokemon3.get(j).getName());

                    
                 
            
        }
            break;
                        case 4: PlayerFrame.caughtPokemon4.add(kp);
                 PlayerFrame.Pokemoncombobox4.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon4.size(); j++){
            
            PlayerFrame.Pokemoncombobox4.addItem(PlayerFrame.caughtPokemon4.get(j).getName());

                    
                 
            
        }
            break;
                            case 5: PlayerFrame.caughtPokemon5.add(kp);
                 PlayerFrame.Pokemoncombobox5.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon5.size(); j++){
            
            PlayerFrame.Pokemoncombobox5.addItem(PlayerFrame.caughtPokemon5.get(j).getName());

                    
                 
            
        }
            break;
                                case 6: PlayerFrame.caughtPokemon6.add(kp);
                 PlayerFrame.Pokemoncombobox6.removeAllItems();
            for(int j=0; j<PlayerFrame.caughtPokemon6.size(); j++){
            
            PlayerFrame.Pokemoncombobox6.addItem(PlayerFrame.caughtPokemon6.get(j).getName());

                    
                 
            
        }
            break;
                
        }
            
        for(int j=0; j<TabloFrame.labelList.size(); j++){
         if(TabloFrame.labelList.get(j).getText()==kp.getName()){
             TabloFrame.labelList.get(j).setText(null);
            TabloFrame.labelList.get(j).setOpaque(false);
         }
      
    }
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables

    private void myinitComponents() {
jComboBox1.removeAllItems();

    }
}
