/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.me.pokemongame;

import javax.swing.JOptionPane;

/**
 *
 * @author nikos
 */
public class PokeCenterFrame extends javax.swing.JFrame {

    private int numberOfPlayer;
    /**
     * Creates new form PokeCenterFrame
     */
    public PokeCenterFrame(int anumberOfPlayer) {
        initComponents();
        this.numberOfPlayer=anumberOfPlayer;
        faintedCombobox.removeAllItems();
        if(numberOfPlayer==1){
            for(int i=0; i<PlayerFrame.caughtPokemon1.size(); i++){
                if(!PlayerFrame.caughtPokemon1.get(i).isAlive())
                    faintedCombobox.addItem(PlayerFrame.caughtPokemon1.get(i).getName());
            }
        }
        else if(numberOfPlayer==2){
            for(int i=0; i<PlayerFrame.caughtPokemon2.size(); i++){
                if(!PlayerFrame.caughtPokemon2.get(i).isAlive())
                    faintedCombobox.addItem(PlayerFrame.caughtPokemon2.get(i).getName());
            }
        }
            
         else if(numberOfPlayer==3){
            for(int i=0; i<PlayerFrame.caughtPokemon3.size(); i++){
                if(!PlayerFrame.caughtPokemon3.get(i).isAlive())
                    faintedCombobox.addItem(PlayerFrame.caughtPokemon3.get(i).getName());
            }
        }
         else if(numberOfPlayer==4){
            for(int i=0; i<PlayerFrame.caughtPokemon4.size(); i++){
                if(!PlayerFrame.caughtPokemon4.get(i).isAlive())
                    faintedCombobox.addItem(PlayerFrame.caughtPokemon4.get(i).getName());
            }
        
    }
         else if(numberOfPlayer==5){
            for(int i=0; i<PlayerFrame.caughtPokemon5.size(); i++){
                if(!PlayerFrame.caughtPokemon5.get(i).isAlive())
                    faintedCombobox.addItem(PlayerFrame.caughtPokemon5.get(i).getName());
            }
        
    }
         else if(numberOfPlayer==6){
            for(int i=0; i<PlayerFrame.caughtPokemon6.size(); i++){
                if(!PlayerFrame.caughtPokemon6.get(i).isAlive())
                    faintedCombobox.addItem(PlayerFrame.caughtPokemon6.get(i).getName());
            }
        
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        faintedCombobox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        faintedCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel2.setText("Your fainted Pokemon:");

        jButton1.setText("REVIVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faintedCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(faintedCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String fainted=(String) faintedCombobox.getSelectedItem();
        if(numberOfPlayer==1){
    
            for(int i=0; i<PlayerFrame.caughtPokemon1.size(); i++){
                if(PlayerFrame.caughtPokemon1.get(i).getName()==fainted){
                    PlayerFrame.caughtPokemon1.get(i).setAlive(true);
            }
        }
        }
        else if(numberOfPlayer==2){
            for(int i=0; i<PlayerFrame.caughtPokemon2.size(); i++){
                if(PlayerFrame.caughtPokemon2.get(i).getName()==fainted){
                    PlayerFrame.caughtPokemon2.get(i).setAlive(true);
            }
        }}
            
         else if(numberOfPlayer==3){
            for(int i=0; i<PlayerFrame.caughtPokemon3.size(); i++){
               if(PlayerFrame.caughtPokemon3.get(i).getName()==fainted){
                    PlayerFrame.caughtPokemon3.get(i).setAlive(true);
            }
        }}
         else if(numberOfPlayer==4){
            for(int i=0; i<PlayerFrame.caughtPokemon4.size(); i++){
                if(PlayerFrame.caughtPokemon4.get(i).getName()==fainted){
                    PlayerFrame.caughtPokemon4.get(i).setAlive(true);
            }
            }
    }
         else if(numberOfPlayer==5){
            for(int i=0; i<PlayerFrame.caughtPokemon5.size(); i++){
                if(PlayerFrame.caughtPokemon5.get(i).getName()==fainted){
                    PlayerFrame.caughtPokemon5.get(i).setAlive(true);
            }
        
    }}
         else if(numberOfPlayer==6){
            for(int i=0; i<PlayerFrame.caughtPokemon6.size(); i++){
                if(PlayerFrame.caughtPokemon6.get(i).getName()==fainted){
                    PlayerFrame.caughtPokemon6.get(i).setAlive(true);
            }
                 
    }}
                                                                     JOptionPane.showMessageDialog(rootPane, "Your "+fainted+" is healed!", ":D ", WIDTH);

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox faintedCombobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
