/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.me.pokemongame;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static org.me.pokemongame.PokemonTapaFrame.p;

/**
 *
 * @author user
 */
public class ShowPokemonFrame extends javax.swing.JFrame {
    private String name;
   private int playerNumber;
    /**
     * Creates new form ShowPokemon
     */
    public ShowPokemonFrame(String aName, int aplayerNumber)  {
        this.name=aName;
        this.playerNumber=aplayerNumber;
        initComponents();
        myinitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 306, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 598, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel1, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jLabel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void myinitComponents() {
      ImageIcon  icon = new javax.swing.ImageIcon(getClass().getResource("/org/me/pokemongame/pokemon-tapes/"+name+".png"));
       
           
           

            
             

   
      jLabel1.setIcon(icon);
      
        this.setTitle(name);
    
        switch(playerNumber)
        {
            case 1: 
                for(int i=0; i<PlayerFrame.caughtPokemon1.size(); i++){
                    if(PlayerFrame.caughtPokemon1.get(i).getName()==name){
                        
                        if(PlayerFrame.caughtPokemon1.get(i).isAlive())
                        {
                        jLabel2.setText("Status: OK :)");
                        }
                        else 
                        {
                             jLabel2.setText("Status: FAINT :( ");
                        }
                    }
                }
            break;
                case 2: 
                for(int i=0; i<PlayerFrame.caughtPokemon2.size(); i++){
                    if(PlayerFrame.caughtPokemon2.get(i).getName()==name){
                        
                        if(PlayerFrame.caughtPokemon2.get(i).isAlive())
                        {
                        jLabel2.setText("Status: OK :)");
                        }
                        else 
                        {
                             jLabel2.setText("Status: FAINT :( ");
                        }
                    }
                }
            break;
                    case 3: 
                for(int i=0; i<PlayerFrame.caughtPokemon3.size(); i++){
                    if(PlayerFrame.caughtPokemon3.get(i).getName()==name){
                        
                        if(PlayerFrame.caughtPokemon3.get(i).isAlive())
                        {
                        jLabel2.setText("Status: OK :)");
                        }
                        else 
                        {
                             jLabel2.setText("Status: FAINT :( ");
                        }
                    }
                }
            break;
                        case 4: 
                for(int i=0; i<PlayerFrame.caughtPokemon4.size(); i++){
                    if(PlayerFrame.caughtPokemon4.get(i).getName()==name){
                        
                        if(PlayerFrame.caughtPokemon4.get(i).isAlive())
                        {
                        jLabel2.setText("Status: OK :)");
                        }
                        else 
                        {
                             jLabel2.setText("Status: FAINT :( ");
                        }
                    }
                }
            break;

case 5: 
                for(int i=0; i<PlayerFrame.caughtPokemon5.size(); i++){
                    if(PlayerFrame.caughtPokemon5.get(i).getName()==name){
                        
                        if(PlayerFrame.caughtPokemon5.get(i).isAlive())
                        {
                        jLabel2.setText("Status: OK :)");
                        }
                        else 
                        {
                             jLabel2.setText("Status: FAINT :( ");
                        }
                    }
                }
            break;

case 6: 
                for(int i=0; i<PlayerFrame.caughtPokemon6.size(); i++){
                    if(PlayerFrame.caughtPokemon6.get(i).getName()==name){
                        
                        if(PlayerFrame.caughtPokemon6.get(i).isAlive())
                        {
                        jLabel2.setText("Status: OK :)");
                        }
                        else 
                        {
                             jLabel2.setText("Status: FAINT :( ");
                        }
                    }
                }
            break;
default:
            break;
    





        }
        
        
        
        
        
    }
}
