/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.me.pokemongame;

import java.util.Random;
import static org.me.pokemongame.PlayerFrame.caughtPokemon;
import static org.me.pokemongame.PlayerFrame.caughtPokemon1;
import static org.me.pokemongame.PokemonTapaFrame.p;

/**
 *
 * @author nikos
 */
public class StarterFrame extends javax.swing.JFrame {
private int numberOfPlayers;
    /**
     * Creates new form StarterFrame
     */
    public StarterFrame(int anumberOfPlayers) {
        this.numberOfPlayers=anumberOfPlayers;
        initComponents();
        switch(numberOfPlayers){
            case 2: PlayerButton3.setVisible(false);
            PlayerButton4.setVisible(false);
            PlayerButton5.setVisible(false);
            PlayerButton6.setVisible(false);
                break;
            case 3:PlayerButton4.setVisible(false);
            PlayerButton5.setVisible(false);
                PlayerButton6.setVisible(false);
                break;
            case 4: PlayerButton5.setVisible(false);
                PlayerButton6.setVisible(false);
                break;
            case 5: PlayerButton6.setVisible(false);
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PlayerButton1 = new javax.swing.JButton();
        PlayerButton2 = new javax.swing.JButton();
        PlayerButton3 = new javax.swing.JButton();
        PlayerButton4 = new javax.swing.JButton();
        PlayerButton5 = new javax.swing.JButton();
        PlayerButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Starters!!");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);

        PlayerButton1.setText("Player 1");
        PlayerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerButton1ActionPerformed(evt);
            }
        });

        PlayerButton2.setText("Player 2");
        PlayerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerButton2ActionPerformed(evt);
            }
        });

        PlayerButton3.setText("Player 3");
        PlayerButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerButton3ActionPerformed(evt);
            }
        });

        PlayerButton4.setText("Player 4");
        PlayerButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerButton4ActionPerformed(evt);
            }
        });

        PlayerButton5.setText("Player 5");
        PlayerButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerButton5ActionPerformed(evt);
            }
        });

        PlayerButton6.setText("Player 6");
        PlayerButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Players Choose Your Pokemon");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayerButton6)
                    .addComponent(PlayerButton2))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayerButton3)
                    .addComponent(PlayerButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PlayerButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PlayerButton4)
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerButton2)
                    .addComponent(PlayerButton3))
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerButton1)
                    .addComponent(PlayerButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerButton5)
                    .addComponent(PlayerButton6))
                .addGap(100, 100, 100))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/pokemongame/pokemon-tapes/BackStarter.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerButton2ActionPerformed
 Random r=new Random();
        int index=0;
        index = r.nextInt(Pokemon.starterArray.size());
         p = Pokemon.starterArray.get(index);
        PlayerFrame.caughtPokemon2.add(p);
        PlayerFrame.caughtPokemon.add(p);
        PlayerFrame.Pokemoncombobox2.addItem(p.getName());
        Pokemon.starterArray.remove(p);
                new ShowPokemonFrame(p.getName(),0).setVisible(true);    }                                             
/*
        new ShowPokemonFrame(p.getName()).setVisible(true);    }//GEN-LAST:event_PlayerButton2ActionPerformed
*/
    private void PlayerButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerButton5ActionPerformed
Random r=new Random();
        int index=0;
        index = r.nextInt(Pokemon.starterArray.size());
         p = Pokemon.starterArray.get(index);
        PlayerFrame.caughtPokemon5.add(p);
        PlayerFrame.caughtPokemon.add(p);
        PlayerFrame.Pokemoncombobox5.addItem(p.getName());
        Pokemon.starterArray.remove(p);
        new ShowPokemonFrame(p.getName(),0).setVisible(true);    }  
    /*
        new ShowPokemonFrame(p.getName()).setVisible(true);    }//GEN-LAST:event_PlayerButton5ActionPerformed
*/
    private void PlayerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerButton1ActionPerformed
        Random r=new Random();
        int index=0;
        index = r.nextInt(Pokemon.starterArray.size());
         p = Pokemon.starterArray.get(index);
        PlayerFrame.caughtPokemon1.add(p);
        PlayerFrame.caughtPokemon.add(p);
        PlayerFrame.Pokemoncombobox1.addItem(p.getName());
        Pokemon.starterArray.remove(p);
        new ShowPokemonFrame(p.getName(),0).setVisible(true);    }  
    /*
        new ShowPokemonFrame(p.getName()).setVisible(true);
    }//GEN-LAST:event_PlayerButton1ActionPerformed
*/
    private void PlayerButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerButton3ActionPerformed
Random r=new Random();
        int index=0;
        index = r.nextInt(Pokemon.starterArray.size());
         p = Pokemon.starterArray.get(index);
        PlayerFrame.caughtPokemon3.add(p);
        PlayerFrame.caughtPokemon.add(p);
        PlayerFrame.Pokemoncombobox3.addItem(p.getName());
        Pokemon.starterArray.remove(p);
        new ShowPokemonFrame(p.getName(),0).setVisible(true);    }  
    /*
        new ShowPokemonFrame(p.getName()).setVisible(true);    }//GEN-LAST:event_PlayerButton3ActionPerformed
*/
    private void PlayerButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerButton4ActionPerformed
Random r=new Random();
        int index=0;
        index = r.nextInt(Pokemon.starterArray.size());
         p = Pokemon.starterArray.get(index);
        PlayerFrame.caughtPokemon4.add(p);
        PlayerFrame.caughtPokemon.add(p);
        PlayerFrame.Pokemoncombobox4.addItem(p.getName());
        Pokemon.starterArray.remove(p);
        new ShowPokemonFrame(p.getName(),0).setVisible(true);    }  
    /*
        new ShowPokemonFrame(p.getName()).setVisible(true);    }//GEN-LAST:event_PlayerButton4ActionPerformed
*/
    private void PlayerButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerButton6ActionPerformed
Random r=new Random();
        int index=0;
        index = r.nextInt(Pokemon.starterArray.size());
         p = Pokemon.starterArray.get(index);
        PlayerFrame.caughtPokemon6.add(p);
        PlayerFrame.caughtPokemon.add(p);
        PlayerFrame.Pokemoncombobox6.addItem(p.getName());
        Pokemon.starterArray.remove(p);
        new ShowPokemonFrame(p.getName(),0).setVisible(true);    }  
    /*
        new ShowPokemonFrame(p.getName()).setVisible(true);    }//GEN-LAST:event_PlayerButton6ActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayerButton1;
    private javax.swing.JButton PlayerButton2;
    private javax.swing.JButton PlayerButton3;
    private javax.swing.JButton PlayerButton4;
    private javax.swing.JButton PlayerButton5;
    private javax.swing.JButton PlayerButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
